pipeline:
  name: asdadas
  identifier: asdadas
  tags: {}
  projectIdentifier: vlterragrunt
  orgIdentifier: default
  stages:
    - stage:
        name: asda
        identifier: asda
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            infrastructureDefinitions: <+input>
        tags: {}
