apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    type: front-end
spec:
  type: ClusterIP
  selector:
    app: myapp
    type: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
